# 2x2 Matrix Inversion with NumPy

**Author:**  [Christopher Mathews](https://twitter.com/Paxenterra)

**Date:** 15.01.2022

**Last Update**: 15.01.2022
***

## Introduction

An inverse matrix is useful for solving problems involving the dividing of matrix values; unlike multiplacation, division of matrices is not possible. Similar to number recipricals: $ 4\; reciprical $ can be written $ \frac{1}{4}\; or \; 4^{-1} $. Matrices alternatively have inverse values, $ A, A^{1} $ which can be used for extracting out the divided values by means of multiplication by inverse; a very nearly solution where division is not possible.

In this notebook, we will explore how to use the NumPy library to create a matrix, determine if it can be inverted, code the preparation work for inversing a matrix, and then check our results against know properties of matrix inversions.

### Exploring the 2 x 2 matrix

Below is a theoretical 2x2 square matrix. 

$ A = \begin{matrix} 
a & b\\
c & d
\end{matrix} $

Not all matrices can be inversed. 

Inverse hesitant matricies are known as singular, their compliant counterparts are known binarily as non-singular. We classify the matrix in either category by calculating the determinent. 

Below we see $ given $ matrix $ A $, the determinent indicates what we look for in order to make a classification. 

>$ Given\: \det(A) \neq 0 $ *then* $ A $ is a non-singular matrix and **can** be inversed.

***OR***

>$ Given\: \det(A) = $ *then* $ A $ is a singular matrix and **cannot** be inversed.

$ Given\: \det(A) = $ *then* $ A $ is a singular matrix and **cannot** be inversed.

### Using NumPy to build the matrix

<div class="alert alert-block alert-info"> <b>NOTE</b> NumPy .matrix method docs reccomends using narray even instead of the .matrix method, as the class maybe removed. </div>

In [1]:
import numpy as np
#numpy array can be build using list of lists.
a = np.array([[2,0.5], [1,0]])
print(a)
#Observe the dimensions
print('Matrix "A" is a square, with dimensions:', a.shape)

[[2.  0.5]
 [1.  0. ]]
Matrix "A" is a square, with dimensions: (2, 2)


### Working out the determinent

The formula for working out if the derminent is 0 in the example below is $ ad - bc $

$ \det (A) = \begin{vmatrix}
a & b\\
c & d
\end{vmatrix}(a\times d)-(b\times c) $

In [2]:
#using our array let's work the determinent out manually first.
det = (a[0,0] * a[1,1])-(a[0,1] * a[1,0])

if det != 0:
    print(det, "Matrix 'A' is a non-singular and **can** be inversed.", sep = '\n')
else:
    print(det, "Matrix 'A' is singular  and **cannot** be inversed.")

-0.5
Matrix 'A' is a non-singular and **can** be inversed.


Or, you can use NumPy's built in determinent function.

In [3]:
print (np.linalg.det(a).astype('float32'))


-0.5


### Inverse Matrix Properties

Now we know $ A $ can be inversed. Let's learn a little more about the properties of an inversed matrix.

Notationally, our inverse matrix is:     

$ A^{1} $

* The product of $ AA^{1} = I $
* $ A^{1}A = I $ is also true.
* Order of magnitude does not matter. Switching position always returns $ I $

$ I $ = Identity matrix

Identity matrices value are nil, except those on the leading diaganol, which are 1. We will use these expressions as an evaluating method to test the trueness of inversion of $ A $ at the end.

In [4]:
#To satisfy your curiosity - NumPy can build a 2x2 identity  matrix.
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


### Inverting $ A $

$ A^{1}= \frac{1}{ad-bc} \begin{vmatrix}
d & -b\\
-c & a
\end{vmatrix} $

Above we see the expression for caluclating the inverse matrix. If you look closely you can see the values $ a $ and $ d $ have swapped positions, $ b, c $ have become negatives. A matrix with positions swapped and turned to negative is known as 'adjoint. Let's go ahead and adjoint matrix $ A $.

In [5]:
#Reminder of Matrix A and value positions.
print(a)

[[2.  0.5]
 [1.  0. ]]


In [6]:
#we will need A for AA1 = I, so we will make a copy of A to position adjoint
copy_a = np.copy(a)
#Swap position a with d
copy_a[0,0], copy_a[1,1] = copy_a[1,1], copy_a[0,0]
#Convert positions b and c to negatives
copy_a[0,1], copy_a[1,0] = -abs(copy_a[0,1]), -abs(copy_a[1,0])

adj = copy_a
print(adj)

[[ 0.  -0.5]
 [-1.   2. ]]


To calculate $ A^{-1} $, we first solve the left side of the expression using the new adjoint matrix.

Part 1: $ \frac{1}{ad-bc} $

In [7]:
top = 1
bottom = (adj[0,0] * adj[1,1])-(adj[0,1] * adj[1,0])
fraction = top / bottom
fraction

-2.0

Part 2: $ \;-2 \begin{pmatrix}
0 & -0.5\\
-1 & 2
\end{pmatrix} $

In [8]:
#Multiplying adjoint values by left side.
a1 = adj * fraction
print(a1)

[[-0.  1.]
 [ 2. -4.]]


### Checking Results

Great, we have $ A^{1} $, we can check its correct by using a built in inverse calcluation that would have done all this hard work for us...the output should be the same as a1.

In [9]:
#np method to calculare inverse. Looks good.
np.linalg.inv(a)

array([[ 0.,  1.],
       [ 2., -4.]])

We can further confirm our result holds up by applying the inverse matrix properties defined earlier:

* The product of $ AA^{1} = I $
* $ A^{1}A = I $
* Order of magnitude does not matter. Switching position always returns $ I $

Remember an identity matrix is filled with nils, apart from the leading diaganol which is populated with '1' values.

In [10]:
#We can use an np method to calculate the product of two matrices
np.matmul(a, a1)

array([[1., 0.],
       [0., 1.]])

In [11]:
#The same should be true inverse...
#We can use an np method to calculate the product of two matrices
np.matmul(a1, a)

array([[1., 0.],
       [0., 1.]])

If you don't fancy computing matrix inverse, NumPy does indeed have you covered. However, I hope if you read through you now understand the working components behind inversing matricies.

In [12]:
#np method to inverse matrix
print(np.linalg.inv(a))

[[ 0.  1.]
 [ 2. -4.]]


# Acknowledgements

The matrix determenent, adjoint and inverse expressions were learnt from this [Linear Algebra course](https://www.udemy.com/course/linear-algebra-for-beginners-matrices-and-vector-spaces).